; ModuleID = '/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a/[inter]crypto--ui--libcrypto-lib-ui_null.o.i'
source_filename = "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a/[inter]crypto--ui--libcrypto-lib-ui_null.o.i"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.ui_method_st = type { i8*, i32 (%struct.ui_st*)*, i32 (%struct.ui_st*, %struct.ui_string_st*)*, i32 (%struct.ui_st*)*, i32 (%struct.ui_st*, %struct.ui_string_st*)*, i32 (%struct.ui_st*)*, i8* (%struct.ui_st*, i8*)*, void (%struct.ui_st*, i8*)*, i8* (%struct.ui_st*, i8*, i8*)*, %struct.crypto_ex_data_st }
%struct.ui_st = type { %struct.ui_method_st*, %struct.stack_st_UI_STRING*, i8*, %struct.crypto_ex_data_st, i32, i8* }
%struct.stack_st_UI_STRING = type opaque
%struct.ui_string_st = type { i32, i8*, i32, i8*, i64, %union.anon, i32 }
%union.anon = type { %struct.anon.0 }
%struct.anon.0 = type { i8*, i8*, i8* }
%struct.crypto_ex_data_st = type { %struct.stack_st_void* }
%struct.stack_st_void = type opaque

@ui_null = internal constant %struct.ui_method_st { i8* getelementptr inbounds ([16 x i8], [16 x i8]* @.str, i32 0, i32 0), i32 (%struct.ui_st*)* null, i32 (%struct.ui_st*, %struct.ui_string_st*)* null, i32 (%struct.ui_st*)* null, i32 (%struct.ui_st*, %struct.ui_string_st*)* null, i32 (%struct.ui_st*)* null, i8* (%struct.ui_st*, i8*)* null, void (%struct.ui_st*, i8*)* null, i8* (%struct.ui_st*, i8*, i8*)* null, %struct.crypto_ex_data_st zeroinitializer }, align 8
@.str = private unnamed_addr constant [16 x i8] c"OpenSSL NULL UI\00", align 1

; Function Attrs: nounwind uwtable
define %struct.ui_method_st* @UI_null() #0 !dbg !105 {
entry:
  ret %struct.ui_method_st* @ui_null, !dbg !109
}

attributes #0 = { nounwind uwtable "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!102, !103}
!llvm.ident = !{!104}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "clang version 3.9.0 (tags/RELEASE_390/final)", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, globals: !12)
!1 = !DIFile(filename: "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a/[inter]crypto--ui--libcrypto-lib-ui_null.o.i", directory: "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a")
!2 = !{!3}
!3 = !DICompositeType(tag: DW_TAG_enumeration_type, name: "UI_string_types", file: !4, line: 286, size: 32, align: 32, elements: !5)
!4 = !DIFile(filename: "include/openssl/ui.h", directory: "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a")
!5 = !{!6, !7, !8, !9, !10, !11}
!6 = !DIEnumerator(name: "UIT_NONE", value: 0)
!7 = !DIEnumerator(name: "UIT_PROMPT", value: 1)
!8 = !DIEnumerator(name: "UIT_VERIFY", value: 2)
!9 = !DIEnumerator(name: "UIT_BOOLEAN", value: 3)
!10 = !DIEnumerator(name: "UIT_INFO", value: 4)
!11 = !DIEnumerator(name: "UIT_ERROR", value: 5)
!12 = !{!13}
!13 = distinct !DIGlobalVariable(name: "ui_null", scope: !0, file: !14, line: 12, type: !15, isLocal: true, isDefinition: true, variable: %struct.ui_method_st* @ui_null)
!14 = !DIFile(filename: "crypto/ui/ui_null.c", directory: "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a")
!15 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !16)
!16 = !DIDerivedType(tag: DW_TAG_typedef, name: "UI_METHOD", file: !17, line: 148, baseType: !18)
!17 = !DIFile(filename: "include/openssl/ossl_typ.h", directory: "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a")
!18 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ui_method_st", file: !19, line: 20, size: 640, align: 64, elements: !20)
!19 = !DIFile(filename: "crypto/ui/ui_locl.h", directory: "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a")
!20 = !{!21, !24, !52, !86, !87, !88, !89, !93, !97, !101}
!21 = !DIDerivedType(tag: DW_TAG_member, name: "name", scope: !18, file: !19, line: 21, baseType: !22, size: 64, align: 64)
!22 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !23, size: 64, align: 64)
!23 = !DIBasicType(name: "char", size: 8, align: 8, encoding: DW_ATE_signed_char)
!24 = !DIDerivedType(tag: DW_TAG_member, name: "ui_open_session", scope: !18, file: !19, line: 31, baseType: !25, size: 64, align: 64, offset: 64)
!25 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !26, size: 64, align: 64)
!26 = !DISubroutineType(types: !27)
!27 = !{!28, !29}
!28 = !DIBasicType(name: "int", size: 32, align: 32, encoding: DW_ATE_signed)
!29 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !30, size: 64, align: 64)
!30 = !DIDerivedType(tag: DW_TAG_typedef, name: "UI", file: !17, line: 147, baseType: !31)
!31 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ui_st", file: !19, line: 94, size: 384, align: 64, elements: !32)
!32 = !{!33, !35, !38, !40, !48, !49}
!33 = !DIDerivedType(tag: DW_TAG_member, name: "meth", scope: !31, file: !19, line: 95, baseType: !34, size: 64, align: 64)
!34 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !15, size: 64, align: 64)
!35 = !DIDerivedType(tag: DW_TAG_member, name: "strings", scope: !31, file: !19, line: 96, baseType: !36, size: 64, align: 64, offset: 64)
!36 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !37, size: 64, align: 64)
!37 = !DICompositeType(tag: DW_TAG_structure_type, name: "stack_st_UI_STRING", file: !4, line: 280, flags: DIFlagFwdDecl)
!38 = !DIDerivedType(tag: DW_TAG_member, name: "user_data", scope: !31, file: !19, line: 99, baseType: !39, size: 64, align: 64, offset: 128)
!39 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64, align: 64)
!40 = !DIDerivedType(tag: DW_TAG_member, name: "ex_data", scope: !31, file: !19, line: 100, baseType: !41, size: 64, align: 64, offset: 192)
!41 = !DIDerivedType(tag: DW_TAG_typedef, name: "CRYPTO_EX_DATA", file: !17, line: 167, baseType: !42)
!42 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "crypto_ex_data_st", file: !43, line: 86, size: 64, align: 64, elements: !44)
!43 = !DIFile(filename: "include/openssl/crypto.h", directory: "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a")
!44 = !{!45}
!45 = !DIDerivedType(tag: DW_TAG_member, name: "sk", scope: !42, file: !43, line: 87, baseType: !46, size: 64, align: 64)
!46 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !47, size: 64, align: 64)
!47 = !DICompositeType(tag: DW_TAG_structure_type, name: "stack_st_void", file: !43, line: 87, flags: DIFlagFwdDecl)
!48 = !DIDerivedType(tag: DW_TAG_member, name: "flags", scope: !31, file: !19, line: 104, baseType: !28, size: 32, align: 32, offset: 256)
!49 = !DIDerivedType(tag: DW_TAG_member, name: "lock", scope: !31, file: !19, line: 106, baseType: !50, size: 64, align: 64, offset: 320)
!50 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !51, size: 64, align: 64)
!51 = !DIDerivedType(tag: DW_TAG_typedef, name: "CRYPTO_RWLOCK", file: !43, line: 67, baseType: null)
!52 = !DIDerivedType(tag: DW_TAG_member, name: "ui_write_string", scope: !18, file: !19, line: 32, baseType: !53, size: 64, align: 64, offset: 128)
!53 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !54, size: 64, align: 64)
!54 = !DISubroutineType(types: !55)
!55 = !{!28, !29, !56}
!56 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !57, size: 64, align: 64)
!57 = !DIDerivedType(tag: DW_TAG_typedef, name: "UI_STRING", file: !4, line: 279, baseType: !58)
!58 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ui_string_st", file: !19, line: 61, size: 576, align: 64, elements: !59)
!59 = !{!60, !61, !64, !65, !66, !70, !85}
!60 = !DIDerivedType(tag: DW_TAG_member, name: "type", scope: !58, file: !19, line: 62, baseType: !3, size: 32, align: 32)
!61 = !DIDerivedType(tag: DW_TAG_member, name: "out_string", scope: !58, file: !19, line: 63, baseType: !62, size: 64, align: 64, offset: 64)
!62 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !63, size: 64, align: 64)
!63 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !23)
!64 = !DIDerivedType(tag: DW_TAG_member, name: "input_flags", scope: !58, file: !19, line: 64, baseType: !28, size: 32, align: 32, offset: 128)
!65 = !DIDerivedType(tag: DW_TAG_member, name: "result_buf", scope: !58, file: !19, line: 69, baseType: !22, size: 64, align: 64, offset: 192)
!66 = !DIDerivedType(tag: DW_TAG_member, name: "result_len", scope: !58, file: !19, line: 74, baseType: !67, size: 64, align: 64, offset: 256)
!67 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !68, line: 216, baseType: !69)
!68 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h", directory: "/home/ubuntu_1604/Desktop/openssl_bcmake_outputs/[lib]libcrypto.a")
!69 = !DIBasicType(name: "long unsigned int", size: 64, align: 64, encoding: DW_ATE_unsigned)
!70 = !DIDerivedType(tag: DW_TAG_member, name: "_", scope: !58, file: !19, line: 88, baseType: !71, size: 192, align: 64, offset: 320)
!71 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !58, file: !19, line: 75, size: 192, align: 64, elements: !72)
!72 = !{!73, !79}
!73 = !DIDerivedType(tag: DW_TAG_member, name: "string_data", scope: !71, file: !19, line: 82, baseType: !74, size: 128, align: 64)
!74 = distinct !DICompositeType(tag: DW_TAG_structure_type, scope: !71, file: !19, line: 76, size: 128, align: 64, elements: !75)
!75 = !{!76, !77, !78}
!76 = !DIDerivedType(tag: DW_TAG_member, name: "result_minsize", scope: !74, file: !19, line: 77, baseType: !28, size: 32, align: 32)
!77 = !DIDerivedType(tag: DW_TAG_member, name: "result_maxsize", scope: !74, file: !19, line: 79, baseType: !28, size: 32, align: 32, offset: 32)
!78 = !DIDerivedType(tag: DW_TAG_member, name: "test_buf", scope: !74, file: !19, line: 81, baseType: !62, size: 64, align: 64, offset: 64)
!79 = !DIDerivedType(tag: DW_TAG_member, name: "boolean_data", scope: !71, file: !19, line: 87, baseType: !80, size: 192, align: 64)
!80 = distinct !DICompositeType(tag: DW_TAG_structure_type, scope: !71, file: !19, line: 83, size: 192, align: 64, elements: !81)
!81 = !{!82, !83, !84}
!82 = !DIDerivedType(tag: DW_TAG_member, name: "action_desc", scope: !80, file: !19, line: 84, baseType: !62, size: 64, align: 64)
!83 = !DIDerivedType(tag: DW_TAG_member, name: "ok_chars", scope: !80, file: !19, line: 85, baseType: !62, size: 64, align: 64, offset: 64)
!84 = !DIDerivedType(tag: DW_TAG_member, name: "cancel_chars", scope: !80, file: !19, line: 86, baseType: !62, size: 64, align: 64, offset: 128)
!85 = !DIDerivedType(tag: DW_TAG_member, name: "flags", scope: !58, file: !19, line: 91, baseType: !28, size: 32, align: 32, offset: 512)
!86 = !DIDerivedType(tag: DW_TAG_member, name: "ui_flush", scope: !18, file: !19, line: 37, baseType: !25, size: 64, align: 64, offset: 192)
!87 = !DIDerivedType(tag: DW_TAG_member, name: "ui_read_string", scope: !18, file: !19, line: 38, baseType: !53, size: 64, align: 64, offset: 256)
!88 = !DIDerivedType(tag: DW_TAG_member, name: "ui_close_session", scope: !18, file: !19, line: 39, baseType: !25, size: 64, align: 64, offset: 320)
!89 = !DIDerivedType(tag: DW_TAG_member, name: "ui_duplicate_data", scope: !18, file: !19, line: 44, baseType: !90, size: 64, align: 64, offset: 384)
!90 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !91, size: 64, align: 64)
!91 = !DISubroutineType(types: !92)
!92 = !{!39, !29, !39}
!93 = !DIDerivedType(tag: DW_TAG_member, name: "ui_destroy_data", scope: !18, file: !19, line: 45, baseType: !94, size: 64, align: 64, offset: 448)
!94 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !95, size: 64, align: 64)
!95 = !DISubroutineType(types: !96)
!96 = !{null, !29, !39}
!97 = !DIDerivedType(tag: DW_TAG_member, name: "ui_construct_prompt", scope: !18, file: !19, line: 53, baseType: !98, size: 64, align: 64, offset: 512)
!98 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !99, size: 64, align: 64)
!99 = !DISubroutineType(types: !100)
!100 = !{!22, !29, !62, !62}
!101 = !DIDerivedType(tag: DW_TAG_member, name: "ex_data", scope: !18, file: !19, line: 58, baseType: !41, size: 64, align: 64, offset: 576)
!102 = !{i32 2, !"Dwarf Version", i32 4}
!103 = !{i32 2, !"Debug Info Version", i32 3}
!104 = !{!"clang version 3.9.0 (tags/RELEASE_390/final)"}
!105 = distinct !DISubprogram(name: "UI_null", scope: !14, file: !14, line: 23, type: !106, isLocal: false, isDefinition: true, scopeLine: 24, flags: DIFlagPrototyped, isOptimized: false, unit: !0, variables: !108)
!106 = !DISubroutineType(types: !107)
!107 = !{!34}
!108 = !{}
!109 = !DILocation(line: 25, column: 5, scope: !105)
